POST http://localhost:8008/user-api/user
Content-Type: application/json

{
    "name":"Sairm",
    "age":18,
    "email":"sairam@gmail.com",
    "password":"sairam"
}

### user login(Authentication)
POST http://localhost:8008/user-api/user-login
Content-Type: application/json

{
    "name":"Saisrm",
    "age":18,
    "email":"sairam@gmail.com",
    "password":"sairam"
}


###Read all users
GET  http://localhost:8008/user-api/users

###Read user by name
GET http://localhost:8008/user-api/user?name=Sairam

###Read user by name
GET http://localhost:8008/user-api/user/68ecf0f893eff1b416de3313

###Read user by id
PUT http://localhost:8008/user-api/user/68eddc6eb568baaedadad007
Content-Type: application/json

{
    "_id":"68eddc6eb568baaedadad007",
    "name":"Sairam Anumala",
    "age":18,
    "email":"saianumala02@gmail.com"
}

###Delete user by id
DELETE http://localhost:8008/user-api/user/68edc8d4ce986e8cd20d403d

### req for prottected route
GET http://localhost:8008/user-api/protected
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiU2FpcmFtIiwiaWF0IjoxNzYwNTA1NDE3LCJleHAiOjE3NjA1MDU1Mzd9.iXRtYXbLB4R1FFzqkNMnfPXw_rOwvtk7hDiXLSHf1co